export const myProduct = [
    {
        id: 1,
        title: "Classic White T-Shirt",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["White"],
        image: "/images/classic-white-t-shirt.jpg",
        description: "Soft cotton white t-shirt for everyday casual wear.",
        price: 19.99,
        discount: 10,
        stock: 120
    },
    {
        id: 2,
        title: "Black Oversized T-Shirt",
        category: "Men",
        size: ["M", "L", "XL"],
        color: ["Black"],
        image: "/images/black-oversized-t-shirt.jpg",
        description: "Modern oversized black t-shirt with premium cotton.",
        price: 24.99,
        discount: 15,
        stock: 80
    },
    {
        id: 3,
        title: "Slim Fit Polo Shirt",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["Navy Blue", "Black", "Grey", "White"],
        image: "/images/slim-fit-polo-shirt.jpg",
        description: "Elegant polo shirt for casual and office wear.",
        price: 29.99,
        discount: 12,
        stock: 60
    },
    {
        id: 4,
        title: "Blue Denim Jacket",
        category: "Men",
        size: ["M", "L", "XL"],
        color: ["Light Blue", "Dark Blue"],
        image: "/images/blue-denim-jacket.jpg",
        description: "Classic denim jacket with modern fit.",
        price: 59.99,
        discount: 20,
        stock: 45
    },
    {
        id: 5,
        title: "Grey Hoodie",
        category: "Men",
        size: ["M", "L", "XL", "XXL"],
        color: ["Grey", "Dark Grey"],
        image: "/images/grey-hoodie.jpg",
        description: "Warm fleece hoodie for cold weather.",
        price: 39.99,
        discount: 15,
        stock: 75
    },
    {
        id: 6,
        title: "Women's Floral Dress",
        category: "Women",
        size: ["S", "M", "L"],
        color: ["Floral Print", "Pink Floral", "Blue Floral"],
        image: "/images/womens-floral-dress.jpg",
        description: "Beautiful floral summer dress.",
        price: 49.99,
        discount: 18,
        stock: 55
    },
    {
        id: 7,
        title: "Women's Black Blazer",
        category: "Women",
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        image: "/images/womens-black-blazer.jpg",
        description: "Professional tailored blazer.",
        price: 69.99,
        discount: 25,
        stock: 40
    },
    {
        id: 8,
        title: "Pink Oversized Hoodie",
        category: "Women",
        size: ["S", "M", "L"],
        color: ["Pink", "Baby Pink"],
        image: "/images/pink-oversized-hoodie.jpg",
        description: "Soft oversized hoodie for comfort.",
        price: 42.99,
        discount: 10,
        stock: 62
    },
    {
        id: 9,
        title: "Women's Blue Jeans",
        category: "Women",
        size: ["26", "28", "30", "32"],
        color: ["Blue Denim", "Light Denim"],
        image: "/images/womens-blue-jeans.jpg",
        description: "Slim fit stretch denim jeans.",
        price: 44.99,
        discount: 15,
        stock: 90
    },
    {
        id: 10,
        title: "Casual White Sneakers",
        category: "Shoes",
        size: ["39", "40", "41", "42", "43"],
        color: ["White"],
        image: "/images/casual-white-sneakers.jpg",
        description: "Comfortable sneakers for daily use.",
        price: 59.99,
        discount: 20,
        stock: 110
    },
    {
        id: 11,
        title: "Running Shoes",
        category: "Shoes",
        size: ["40", "41", "42", "43", "44"],
        color: ["Black Red", "Grey Blue", "All Black"],
        image: "/images/running-shoes.jpg",
        description: "Lightweight breathable running shoes.",
        price: 79.99,
        discount: 18,
        stock: 85
    },
    {
        id: 12,
        title: "Leather Backpack",
        category: "Bags",
        size: ["One Size"],
        color: ["Brown", "Black"],
        image: "/images/leather-backpack.jpg",
        description: "Stylish leather backpack for travel.",
        price: 69.99,
        discount: 15,
        stock: 35
    },
    {
        id: 13,
        title: "Women's Handbag",
        category: "Bags",
        size: ["One Size"],
        color: ["Beige", "Black", "Maroon"],
        image: "/images/womens-handbag.jpg",
        description: "Elegant handbag for daily use.",
        price: 54.99,
        discount: 12,
        stock: 50
    },
    {
        id: 14,
        title: "Digital Sports Watch",
        category: "Watches",
        size: ["One Size"],
        color: ["Matte Black", "Army Green"],
        image: "/images/digital-sports-watch.jpg",
        description: "Water-resistant sports watch.",
        price: 89.99,
        discount: 22,
        stock: 30
    },
    {
        id: 15,
        title: "Luxury Leather Watch",
        category: "Watches",
        size: ["One Size"],
        color: ["Gold Brown", "Silver Black"],
        image: "/images/luxury-leather-watch.jpg",
        description: "Elegant leather strap watch.",
        price: 119.99,
        discount: 20,
        stock: 25
    },
    {
        id: 16,
        title: "Men's Cargo Pants",
        category: "Men",
        size: ["30", "32", "34", "36"],
        color: ["Khaki", "Olive Green", "Black"],
        image: "/images/mens-cargo-pants.jpg",
        description: "Multi-pocket cargo pants.",
        price: 49.99,
        discount: 10,
        stock: 65
    },
    {
        id: 17,
        title: "Women's Pleated Skirt",
        category: "Women",
        size: ["S", "M", "L"],
        color: ["Beige", "Black", "Pink"],
        image: "/images/womens-pleated-skirt.jpg",
        description: "Elegant pleated skirt.",
        price: 36.99,
        discount: 15,
        stock: 58
    },
    {
        id: 18,
        title: "Winter Puffer Jacket",
        category: "Men",
        size: ["M", "L", "XL"],
        color: ["Black", "Navy Blue", "Dark Green"],
        image: "/images/winter-puffer-jacket.jpg",
        description: "Warm winter jacket.",
        price: 89.99,
        discount: 25,
        stock: 42
    },
    {
        id: 19,
        title: "Women's Knit Sweater",
        category: "Women",
        size: ["S", "M", "L", "XL"],
        color: ["Cream White", "Mustard Yellow", "Grey"],
        image: "/images/womens-knit-sweater.jpg",
        description: "Soft knitted sweater.",
        price: 39.99,
        discount: 18,
        stock: 70
    },
    {
        id: 20,
        title: "Canvas Crossbody Bag",
        category: "Bags",
        size: ["One Size"],
        color: ["Off-White", "Black", "Olive"],
        image: "/images/canvas-crossbody-bag.jpg",
        description: "Lightweight crossbody bag.",
        price: 34.99,
        discount: 10,
        stock: 95
    },
    {
        id: 21,
        title: "Striped Casual Shirt",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["Blue White Stripes", "Grey White Stripes"],
        image: "/images/striped-casual-shirt.jpg",
        description: "Lightweight striped shirt for daily wear.",
        price: 27.99,
        discount: 12,
        stock: 70
    },
    {
        id: 22,
        title: "Basic Black T-Shirt",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        image: "/images/basic-black-t-shirt.jpg",
        description: "Simple black t-shirt made from soft cotton.",
        price: 18.99,
        discount: 8,
        stock: 140
    },
    {
        id: 23,
        title: "Checked Flannel Shirt",
        category: "Men",
        size: ["M", "L", "XL"],
        color: ["Red Black Plaid", "Blue Black Plaid"],
        image: "/images/checked-flannel-shirt.jpg",
        description: "Warm flannel shirt for casual winter style.",
        price: 32.99,
        discount: 15,
        stock: 65
    },
    {
        id: 24,
        title: "Men's Sport Shorts",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["Black", "Dark Grey", "Navy"],
        image: "/images/mens-sport-shorts.jpg",
        description: "Breathable shorts for sports and gym.",
        price: 22.99,
        discount: 10,
        stock: 100
    },
    {
        id: 25,
        title: "Slim Fit Jeans",
        category: "Men",
        size: ["30", "32", "34", "36"],
        color: ["Dark Blue", "Black", "Light Blue"],
        image: "/images/slim-fit-jeans.jpg",
        description: "Modern slim fit denim jeans.",
        price: 45.99,
        discount: 18,
        stock: 80
    },
    {
        id: 26,
        title: "Women's Summer Top",
        category: "Women",
        size: ["S", "M", "L"],
        color: ["White", "Yellow", "Mint Green"],
        image: "/images/womens-summer-top.jpg",
        description: "Light and airy top for summer days.",
        price: 25.99,
        discount: 10,
        stock: 90
    },
    {
        id: 27,
        title: "Elegant Evening Dress",
        category: "Women",
        size: ["S", "M", "L", "XL"],
        color: ["Red Wine", "Emerald Green", "Black"],
        image: "/images/elegant-evening-dress.jpg",
        description: "Stylish evening dress for special events.",
        price: 79.99,
        discount: 20,
        stock: 50
    },
    {
        id: 28,
        title: "Casual Long Skirt",
        category: "Women",
        size: ["S", "M", "L"],
        color: ["Brown", "Black", "Floral"],
        image: "/images/casual-long-skirt.jpg",
        description: "Comfortable long skirt for everyday style.",
        price: 34.99,
        discount: 12,
        stock: 60
    },
    {
        id: 29,
        title: "Women's Denim Jacket",
        category: "Women",
        size: ["S", "M", "L", "XL"],
        color: ["Light Blue Denim"],
        image: "/images/womens-denim-jacket.jpg",
        description: "Trendy denim jacket for casual outfits.",
        price: 55.99,
        discount: 18,
        stock: 45
    },
    {
        id: 30,
        title: "High Waist Jeans",
        category: "Women",
        size: ["26", "28", "30", "32"],
        color: ["Blue", "Black"],
        image: "/images/high-waist-jeans.jpg",
        description: "Stretch high-waist denim jeans.",
        price: 48.99,
        discount: 15,
        stock: 85
    },
    {
        id: 31,
        title: "Sports Running Shoes",
        category: "Shoes",
        size: ["39", "40", "41", "42", "43"],
        color: ["Neon Green", "White Blue", "Pink Black"],
        image: "/images/sports-running-shoes.jpg",
        description: "Lightweight shoes for running and jogging.",
        price: 74.99,
        discount: 20,
        stock: 95
    },
    {
        id: 32,
        title: "Leather Formal Shoes",
        category: "Shoes",
        size: ["40", "41", "42", "43", "44"],
        color: ["Black", "Dark Brown"],
        image: "/images/leather-formal-shoes.jpg",
        description: "Elegant leather shoes for formal occasions.",
        price: 89.99,
        discount: 25,
        stock: 60
    },
    {
        id: 33,
        title: "Casual Slip-On Shoes",
        category: "Shoes",
        size: ["39", "40", "41", "42", "43"],
        color: ["Grey", "Navy", "Black"],
        image: "/images/casual-slip-on-shoes.jpg",
        description: "Easy slip-on shoes for everyday comfort.",
        price: 39.99,
        discount: 10,
        stock: 120
    },
    {
        id: 34,
        title: "Women's High Heels",
        category: "Shoes",
        size: ["36", "37", "38", "39", "40"],
        color: ["Nude", "Black", "Red"],
        image: "/images/womens-high-heels.jpg",
        description: "Stylish heels for parties and events.",
        price: 59.99,
        discount: 15,
        stock: 70
    },
    {
        id: 35,
        title: "Canvas Sneakers",
        category: "Shoes",
        size: ["39", "40", "41", "42", "43"],
        color: ["White", "Black", "Navy"],
        image: "/images/canvas-sneakers.jpg",
        description: "Classic canvas sneakers for casual look.",
        price: 29.99,
        discount: 10,
        stock: 150
    },
    {
        id: 36,
        title: "Mini Backpack",
        category: "Bags",
        size: ["One Size"],
        color: ["Black", "Pink", "Baby Blue"],
        image: "/images/mini-backpack.jpg",
        description: "Small stylish backpack for daily use.",
        price: 32.99,
        discount: 12,
        stock: 80
    },
    {
        id: 37,
        title: "Travel Duffel Bag",
        category: "Bags",
        size: ["One Size"],
        color: ["Black", "Grey", "Camouflage"],
        image: "/images/travel-duffel-bag.jpg",
        description: "Large bag for travel and gym use.",
        price: 59.99,
        discount: 18,
        stock: 55
    },
    {
        id: 38,
        title: "Leather Shoulder Bag",
        category: "Bags",
        size: ["One Size"],
        color: ["Tan Brown", "Classic Black"],
        image: "/images/leather-shoulder-bag.jpg",
        description: "Premium shoulder bag with elegant design.",
        price: 64.99,
        discount: 20,
        stock: 40
    },
    {
        id: 39,
        title: "Crossbody Sling Bag",
        category: "Bags",
        size: ["One Size"],
        color: ["Grey", "Black", "Navy"],
        image: "/images/crossbody-sling-bag.jpg",
        description: "Lightweight sling bag for daily use.",
        price: 28.99,
        discount: 10,
        stock: 110
    },
    {
        id: 40,
        title: "Fashion Tote Bag",
        category: "Bags",
        size: ["One Size"],
        color: ["Cream", "Black", "Brown"],
        image: "/images/fashion-tote-bag.jpg",
        description: "Large tote bag for shopping and work.",
        price: 37.99,
        discount: 12,
        stock: 95
    },
    {
        id: 41,
        title: "Basic White Hoodie",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["White"],
        image: "/images/basic-white-hoodie.jpg",
        description: "Simple white hoodie with soft fleece inside.",
        price: 41.99,
        discount: 15,
        stock: 85
    },
    {
        id: 42,
        title: "Street Style Oversized Hoodie",
        category: "Men",
        size: ["M", "L", "XL", "XXL"],
        color: ["Graphic Black", "Graphic Beige"],
        image: "/images/street-style-oversized-hoodie.jpg",
        description: "Trendy oversized hoodie for street fashion.",
        price: 46.99,
        discount: 18,
        stock: 70
    },
    {
        id: 43,
        title: "Men's Training Tank Top",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["Black", "White", "Grey"],
        image: "/images/mens-training-tank-top.jpg",
        description: "Breathable tank top for gym workouts.",
        price: 19.99,
        discount: 10,
        stock: 110
    },
    {
        id: 44,
        title: "Men's Casual Shorts",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["Khaki", "Navy", "Grey"],
        image: "/images/mens-casual-shorts.jpg",
        description: "Comfortable shorts for summer wear.",
        price: 23.99,
        discount: 12,
        stock: 95
    },
    {
        id: 45,
        title: "Men's Formal Shirt White",
        category: "Men",
        size: ["S", "M", "L", "XL"],
        color: ["White"],
        image: "/images/mens-formal-shirt-white.jpg",
        description: "Classic white shirt for office and formal events.",
        price: 33.99,
        discount: 15,
        stock: 60
    },
    {
        id: 46,
        title: "Women's Crop Top",
        category: "Women",
        size: ["S", "M", "L"],
        color: ["Black", "White", "Pink"],
        image: "/images/womens-crop-top.jpg",
        description: "Stylish crop top for modern fashion look.",
        price: 21.99,
        discount: 10,
        stock: 120
    },
    {
        id: 47,
        title: "Women's Hoodie Dress",
        category: "Women",
        size: ["S", "M", "L", "XL"],
        color: ["Grey", "Black"],
        image: "/images/womens-hoodie-dress.jpg",
        description: "Comfortable hoodie dress for casual wear.",
        price: 52.99,
        discount: 20,
        stock: 55
    },
    {
        id: 48,
        title: "Women's Summer Shorts",
        category: "Women",
        size: ["S", "M", "L"],
        color: ["White Denim", "Light Blue Denim"],
        image: "/images/womens-summer-shorts.jpg",
        description: "Light shorts for hot weather.",
        price: 24.99,
        discount: 10,
        stock: 100
    },
    {
        id: 49,
        title: "Women's Formal Pants",
        category: "Women",
        size: ["S", "M", "L", "XL"],
        color: ["Black", "Beige", "Navy Blue"],
        image: "/images/womens-formal-pants.jpg",
        description: "Elegant pants for office and business wear.",
        price: 39.99,
        discount: 15,
        stock: 75
    },
    {
        id: 50,
        title: "Women's Knit Cardigan",
        category: "Women",
        size: ["S", "M", "L", "XL"],
        color: ["Lavender", "Oatmeal", "Sage Green"],
        image: "/images/womens-knit-cardigan.jpg",
        description: "Soft cardigan for cozy and stylish look.",
        price: 44.99,
        discount: 18,
        stock: 65
    }
];